//! Cross-language encode/decode compatibility tests.
//!
//! Reads `tests/vectors_codec.txt` (generated by `tests/lua/gen_codec_vectors.lua`)
//! and verifies that Rust encode/decode produces identical results.
//!
//! The vectors file is NOT in the repo — it is regenerated on demand.
//! Run `tests/run.sh` first to generate vectors.
//!
//! This test requires generated Rust code from `compat.zproto`.
//! The `tests/run.sh` script generates it to `tests/generated/compat.rs`
//! before running `cargo test`.

use std::path::PathBuf;

// The generated code uses `use crate::zproto::{self, Message};` which expects
// a `zproto` module in the current crate. In integration tests, `crate` is the
// test binary, so we re-export the inner zproto module here.
mod zproto {
    pub use ::zproto::zproto::*;
}

// Include the generated code. The run.sh orchestrator generates this file
// from tests/proto/compat.zproto using the Rust emitter.
//
// To generate manually:
//   make -C rust/emitter zproto-gen-rust
//   rust/emitter/zproto-gen-rust tests/proto/compat.zproto --out tests/generated/
include!("generated/compat.rs");

use compat::{AllScalars, EdgeValues, ArraysTest, Inner, Outer, SparseFields};

// Re-export Message from the real zproto crate for use in this test file.
use ::zproto::Message;

// ---- hex helpers ----

fn hex_decode(hex: &str) -> Vec<u8> {
    assert!(hex.len() % 2 == 0, "odd-length hex string: {}", hex);
    (0..hex.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&hex[i..i + 2], 16)
                .unwrap_or_else(|e| panic!("bad hex at offset {}: {}", i, e))
        })
        .collect()
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

// ---- dump formatting (must match gen_codec_vectors.lua exactly) ----

fn format_float(f: f32) -> String {
    format!("f32:{:08x}", f.to_bits())
}

fn needs_escape(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    for b in s.bytes() {
        if b < 32 || b > 126 {
            return true;
        }
        match b as char {
            ';' | '=' | '[' | ']' | '{' | '}' | ',' => return true,
            _ => {}
        }
    }
    false
}

fn hex_string(data: &[u8]) -> String {
    let mut s = String::with_capacity(data.len() * 2);
    for b in data {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

fn format_string(s: &str) -> String {
    if needs_escape(s) {
        format!("str:{}", hex_string(s.as_bytes()))
    } else {
        s.to_string()
    }
}

// ---- dump formatters per struct ----

fn dump_all_scalars(t: &AllScalars) -> String {
    let mut parts = Vec::new();
    parts.push(format!("b={}", t.b));
    parts.push(format!("i32={}", t.i32));
    parts.push(format!("u32={}", t.u32));
    parts.push(format!("i64={}", t.i64));
    parts.push(format!("u64={}", t.u64));
    parts.push(format!("f={}", format_float(t.f)));
    parts.push(format!("s={}", format_string(&t.s)));
    parts.push(format!("bl=hex:{}", hex_string(&t.bl)));
    format!("{{{}}}", parts.join(";"))
}

fn dump_edge_values(t: &EdgeValues) -> String {
    let mut parts = Vec::new();
    parts.push(format!("max_i64={}", t.max_i64));
    parts.push(format!("min_i64={}", t.min_i64));
    parts.push(format!("max_u64={}", t.max_u64));
    parts.push(format!("zero_u64={}", t.zero_u64));
    parts.push(format!("empty_str={}", format_string(&t.empty_str)));
    parts.push(format!("empty_blob=hex:{}", hex_string(&t.empty_blob)));
    parts.push(format!("max_f32={}", format_float(t.max_f32)));
    parts.push(format!("min_f32={}", format_float(t.min_f32)));
    parts.push(format!("neg_f32={}", format_float(t.neg_f32)));
    format!("{{{}}}", parts.join(";"))
}

fn dump_arrays_test(t: &ArraysTest) -> String {
    let ints: Vec<String> = t.ints.iter().map(|v| v.to_string()).collect();
    let strs: Vec<String> = t.strs.iter().map(|v| format_string(v)).collect();
    format!(
        "{{ints=[{}];strs=[{}]}}",
        ints.join(","),
        strs.join(",")
    )
}

fn dump_inner(t: &Inner) -> String {
    format!("{{x={};y={}}}", t.x, format_float(t.y))
}

fn dump_outer(t: &Outer) -> String {
    format!(
        "{{val={};name={}}}",
        dump_inner(&t.val),
        format_string(&t.name)
    )
}

fn dump_sparse_fields(t: &SparseFields) -> String {
    let mut parts = Vec::new();
    parts.push(format!("a={}", t.a));
    parts.push(format!("b={}", t.b));
    parts.push(format!("c={}", t.c));
    format!("{{{}}}", parts.join(";"))
}

// ---- dump parser ----

#[derive(Debug, Clone)]
enum DumpValue {
    Bool(bool),
    Int(i64),
    UInt(u64),
    Float(f32),
    Str(String),
    Blob(Vec<u8>),
    Array(Vec<DumpValue>),
    Struct(Vec<(String, DumpValue)>),
}

struct DumpParser<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> DumpParser<'a> {
    fn new(s: &'a str) -> Self {
        Self {
            data: s.as_bytes(),
            pos: 0,
        }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.data.len() && self.data[self.pos].is_ascii_whitespace() {
            self.pos += 1;
        }
    }

    fn peek(&self) -> Option<u8> {
        self.data.get(self.pos).copied()
    }

    fn parse_value(&mut self) -> Result<DumpValue, String> {
        self.skip_ws();
        match self.peek() {
            Some(b'{') => self.parse_struct(),
            Some(b'[') => self.parse_array(),
            Some(b't') if self.starts_with("true") => {
                self.pos += 4;
                Ok(DumpValue::Bool(true))
            }
            Some(b'f') if self.starts_with("false") => {
                self.pos += 5;
                Ok(DumpValue::Bool(false))
            }
            Some(b'f') if self.starts_with("f32:") => self.parse_float(),
            Some(b'h') if self.starts_with("hex:") => self.parse_blob(),
            Some(b's') if self.starts_with("str:") => self.parse_escaped_string(),
            Some(c) if c == b'-' || c.is_ascii_digit() => self.parse_number(),
            _ => self.parse_raw_string(),
        }
    }

    fn starts_with(&self, s: &str) -> bool {
        self.data[self.pos..].starts_with(s.as_bytes())
    }

    fn parse_struct(&mut self) -> Result<DumpValue, String> {
        self.pos += 1; // skip '{'
        let mut fields = Vec::new();
        loop {
            self.skip_ws();
            if self.peek() == Some(b'}') {
                self.pos += 1;
                break;
            }
            // parse key
            let key_start = self.pos;
            while self.pos < self.data.len() && self.data[self.pos] != b'=' {
                self.pos += 1;
            }
            let key = String::from_utf8_lossy(&self.data[key_start..self.pos])
                .trim()
                .to_string();
            if self.peek() != Some(b'=') {
                return Err(format!("expected '=' at pos {}", self.pos));
            }
            self.pos += 1; // skip '='
            let value = self.parse_value()?;
            fields.push((key, value));
            self.skip_ws();
            if self.peek() == Some(b';') {
                self.pos += 1;
            }
        }
        Ok(DumpValue::Struct(fields))
    }

    fn parse_array(&mut self) -> Result<DumpValue, String> {
        self.pos += 1; // skip '['
        let mut elems = Vec::new();
        loop {
            self.skip_ws();
            if self.peek() == Some(b']') {
                self.pos += 1;
                break;
            }
            elems.push(self.parse_value()?);
            self.skip_ws();
            if self.peek() == Some(b',') {
                self.pos += 1;
            }
        }
        Ok(DumpValue::Array(elems))
    }

    fn parse_float(&mut self) -> Result<DumpValue, String> {
        self.pos += 4; // skip "f32:"
        let hex_start = self.pos;
        while self.pos < self.data.len() {
            let c = self.data[self.pos];
            if c.is_ascii_hexdigit() {
                self.pos += 1;
            } else {
                break;
            }
        }
        let hex_str = std::str::from_utf8(&self.data[hex_start..self.pos])
            .map_err(|e| e.to_string())?;
        let bits = u32::from_str_radix(hex_str, 16)
            .map_err(|e| e.to_string())?;
        Ok(DumpValue::Float(f32::from_bits(bits)))
    }

    fn parse_blob(&mut self) -> Result<DumpValue, String> {
        self.pos += 4; // skip "hex:"
        let hex_start = self.pos;
        while self.pos < self.data.len() {
            let c = self.data[self.pos];
            if c.is_ascii_hexdigit() {
                self.pos += 1;
            } else {
                break;
            }
        }
        let hex_str = std::str::from_utf8(&self.data[hex_start..self.pos])
            .map_err(|e| e.to_string())?;
        let bytes = hex_decode(hex_str);
        Ok(DumpValue::Blob(bytes))
    }

    fn parse_escaped_string(&mut self) -> Result<DumpValue, String> {
        self.pos += 4; // skip "str:"
        let hex_start = self.pos;
        while self.pos < self.data.len() {
            let c = self.data[self.pos];
            if c.is_ascii_hexdigit() {
                self.pos += 1;
            } else {
                break;
            }
        }
        let hex_str = std::str::from_utf8(&self.data[hex_start..self.pos])
            .map_err(|e| e.to_string())?;
        let bytes = hex_decode(hex_str);
        Ok(DumpValue::Str(
            String::from_utf8(bytes).map_err(|e| e.to_string())?
        ))
    }

    fn parse_number(&mut self) -> Result<DumpValue, String> {
        let start = self.pos;
        if self.peek() == Some(b'-') {
            self.pos += 1;
        }
        while self.pos < self.data.len() && self.data[self.pos].is_ascii_digit() {
            self.pos += 1;
        }
        let num_str = std::str::from_utf8(&self.data[start..self.pos])
            .map_err(|e| e.to_string())?;
        // Try i64 first, then u64
        if let Ok(v) = num_str.parse::<i64>() {
            Ok(DumpValue::Int(v))
        } else if let Ok(v) = num_str.parse::<u64>() {
            Ok(DumpValue::UInt(v))
        } else {
            Err(format!("invalid number: {}", num_str))
        }
    }

    fn parse_raw_string(&mut self) -> Result<DumpValue, String> {
        let start = self.pos;
        while self.pos < self.data.len() {
            let c = self.data[self.pos];
            if c == b';' || c == b',' || c == b'}' || c == b']' || c.is_ascii_whitespace() {
                break;
            }
            self.pos += 1;
        }
        let s = std::str::from_utf8(&self.data[start..self.pos])
            .map_err(|e| e.to_string())?
            .to_string();
        Ok(DumpValue::Str(s))
    }
}

fn parse_dump(s: &str) -> Result<DumpValue, String> {
    let mut parser = DumpParser::new(s);
    parser.parse_value()
}

// ---- construct Rust structs from DumpValue ----

fn dump_get<'a>(v: &'a DumpValue, key: &str) -> Option<&'a DumpValue> {
    match v {
        DumpValue::Struct(fields) => {
            for (k, val) in fields {
                if k == key {
                    return Some(val);
                }
            }
            None
        }
        _ => None,
    }
}

fn as_i64(v: &DumpValue) -> i64 {
    match v {
        DumpValue::Int(n) => *n,
        DumpValue::UInt(n) => *n as i64,
        _ => panic!("expected int, got {:?}", v),
    }
}

fn as_u64(v: &DumpValue) -> u64 {
    match v {
        DumpValue::Int(n) => *n as u64,
        DumpValue::UInt(n) => *n,
        _ => panic!("expected uint, got {:?}", v),
    }
}

fn as_f32(v: &DumpValue) -> f32 {
    match v {
        DumpValue::Float(f) => *f,
        _ => panic!("expected float, got {:?}", v),
    }
}

fn as_string(v: &DumpValue) -> String {
    match v {
        DumpValue::Str(s) => s.clone(),
        _ => panic!("expected string, got {:?}", v),
    }
}

fn as_blob(v: &DumpValue) -> Vec<u8> {
    match v {
        DumpValue::Blob(b) => b.clone(),
        DumpValue::Str(s) => s.as_bytes().to_vec(),
        _ => panic!("expected blob, got {:?}", v),
    }
}

fn as_bool(v: &DumpValue) -> bool {
    match v {
        DumpValue::Bool(b) => *b,
        _ => panic!("expected bool, got {:?}", v),
    }
}

fn as_int_array(v: &DumpValue) -> Vec<i32> {
    match v {
        DumpValue::Array(arr) => arr.iter().map(|e| as_i64(e) as i32).collect(),
        _ => panic!("expected array, got {:?}", v),
    }
}

fn as_string_array(v: &DumpValue) -> Vec<String> {
    match v {
        DumpValue::Array(arr) => arr.iter().map(as_string).collect(),
        _ => panic!("expected array, got {:?}", v),
    }
}

fn build_all_scalars(v: &DumpValue) -> AllScalars {
    AllScalars {
        b: dump_get(v, "b").map(as_bool).unwrap_or(false),
        i32: dump_get(v, "i32").map(|v| as_i64(v) as i32).unwrap_or(0),
        u32: dump_get(v, "u32").map(|v| as_u64(v) as u32).unwrap_or(0),
        i64: dump_get(v, "i64").map(as_i64).unwrap_or(0),
        u64: dump_get(v, "u64").map(as_u64).unwrap_or(0),
        f: dump_get(v, "f").map(as_f32).unwrap_or(0.0),
        s: dump_get(v, "s").map(as_string).unwrap_or_default(),
        bl: dump_get(v, "bl").map(as_blob).unwrap_or_default(),
    }
}

fn build_edge_values(v: &DumpValue) -> EdgeValues {
    EdgeValues {
        max_i64: dump_get(v, "max_i64").map(as_i64).unwrap_or(0),
        min_i64: dump_get(v, "min_i64").map(as_i64).unwrap_or(0),
        max_u64: dump_get(v, "max_u64").map(as_u64).unwrap_or(0),
        zero_u64: dump_get(v, "zero_u64").map(as_u64).unwrap_or(0),
        empty_str: dump_get(v, "empty_str").map(as_string).unwrap_or_default(),
        empty_blob: dump_get(v, "empty_blob").map(as_blob).unwrap_or_default(),
        max_f32: dump_get(v, "max_f32").map(as_f32).unwrap_or(0.0),
        min_f32: dump_get(v, "min_f32").map(as_f32).unwrap_or(0.0),
        neg_f32: dump_get(v, "neg_f32").map(as_f32).unwrap_or(0.0),
    }
}

fn build_arrays_test(v: &DumpValue) -> ArraysTest {
    ArraysTest {
        ints: dump_get(v, "ints").map(as_int_array).unwrap_or_default(),
        strs: dump_get(v, "strs").map(as_string_array).unwrap_or_default(),
    }
}

fn build_inner(v: &DumpValue) -> Inner {
    Inner {
        x: dump_get(v, "x").map(|v| as_i64(v) as i32).unwrap_or(0),
        y: dump_get(v, "y").map(as_f32).unwrap_or(0.0),
    }
}

fn build_outer(v: &DumpValue) -> Outer {
    Outer {
        val: dump_get(v, "val").map(build_inner).unwrap_or_default(),
        name: dump_get(v, "name").map(as_string).unwrap_or_default(),
    }
}

fn build_sparse_fields(v: &DumpValue) -> SparseFields {
    SparseFields {
        a: dump_get(v, "a").map(|v| as_i64(v) as i32).unwrap_or(0),
        b: dump_get(v, "b").map(|v| as_i64(v) as i32).unwrap_or(0),
        c: dump_get(v, "c").map(|v| as_i64(v) as i32).unwrap_or(0),
    }
}

// ---- vector loading ----

struct CodecVector {
    struct_name: String,
    case_name: String,
    dump: String,
    hex: String,
}

fn vectors_path() -> PathBuf {
    if let Ok(p) = std::env::var("ZPROTO_CODEC_VECTORS") {
        return PathBuf::from(p);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("vectors_codec.txt")
}

fn load_vectors() -> Vec<CodecVector> {
    let path = vectors_path();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {}. Run `tests/run.sh` (or `tests/lua/run.sh gen-codec`) first to generate vectors.",
            path.display(),
            e
        )
    });

    let mut vectors = Vec::new();
    let mut current_struct = String::new();
    let mut current_case = String::new();
    let mut current_dump: Option<String> = None;

    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('#') {
            let rest = line[1..].trim();
            if rest == "END" {
                break;
            }
            if rest.starts_with("dump:") {
                current_dump = Some(rest[5..].trim().to_string());
            } else if let Some(colon_pos) = rest.find(':') {
                // "# struct:case" line
                current_struct = rest[..colon_pos].to_string();
                current_case = rest[colon_pos + 1..].to_string();
                current_dump = None;
            }
        } else {
            // hex line
            if let Some(dump) = current_dump.take() {
                vectors.push(CodecVector {
                    struct_name: current_struct.clone(),
                    case_name: current_case.clone(),
                    dump,
                    hex: line.to_string(),
                });
            }
        }
    }

    assert!(!vectors.is_empty(), "no vectors in {}", path.display());
    vectors
}

// ---- tests ----

#[test]
fn rust_encode_matches_golden_vectors() {
    let vectors = load_vectors();
    let mut failures = Vec::new();

    for v in &vectors {
        // Rust generated code always encodes all fields (no optional field
        // support). Lua skips nil fields. Cases that intentionally omit
        // fields (sparse_fields:skip_b, sparse_fields:only_b) cannot produce
        // identical wire format, so skip them in the encode test.
        if v.struct_name == "sparse_fields"
            && (v.case_name == "skip_b" || v.case_name == "only_b")
        {
            continue;
        }

        let encoded_hex = match v.struct_name.as_str() {
            "all_scalars" => {
                let dump_val = parse_dump(&v.dump).expect("parse dump");
                let data = build_all_scalars(&dump_val);
                hex_encode(&data.encode().expect("encode"))
            }
            "edge_values" => {
                let dump_val = parse_dump(&v.dump).expect("parse dump");
                let data = build_edge_values(&dump_val);
                hex_encode(&data.encode().expect("encode"))
            }
            "arrays_test" => {
                let dump_val = parse_dump(&v.dump).expect("parse dump");
                let data = build_arrays_test(&dump_val);
                hex_encode(&data.encode().expect("encode"))
            }
            "outer" => {
                let dump_val = parse_dump(&v.dump).expect("parse dump");
                let data = build_outer(&dump_val);
                hex_encode(&data.encode().expect("encode"))
            }
            "sparse_fields" => {
                let dump_val = parse_dump(&v.dump).expect("parse dump");
                let data = build_sparse_fields(&dump_val);
                hex_encode(&data.encode().expect("encode"))
            }
            other => {
                failures.push(format!("UNKNOWN STRUCT [{}:{}] {}", v.struct_name, v.case_name, other));
                continue;
            }
        };

        if encoded_hex != v.hex {
            failures.push(format!(
                "ENCODE MISMATCH [{}:{}]\n  golden: {}\n  rust:   {}",
                v.struct_name, v.case_name, v.hex, encoded_hex
            ));
        }
    }

    if !failures.is_empty() {
        panic!("{} encode mismatch(es):\n{}", failures.len(), failures.join("\n"));
    }
}

#[test]
fn rust_decode_matches_golden_vectors() {
    let vectors = load_vectors();
    let mut failures = Vec::new();

    for v in &vectors {
        // Same skip as encode test: sparse_fields:skip_b and :only_b omit
        // fields that Rust always encodes. The decoded data is correct
        // (absent fields default to 0), but the dump format differs because
        // Rust's dump includes all fields while Lua's only includes non-nil.
        if v.struct_name == "sparse_fields"
            && (v.case_name == "skip_b" || v.case_name == "only_b")
        {
            continue;
        }

        let binary = hex_decode(&v.hex);
        let decoded_dump = match v.struct_name.as_str() {
            "all_scalars" => {
                let data = AllScalars::decode(&binary).expect("decode");
                dump_all_scalars(&data)
            }
            "edge_values" => {
                let data = EdgeValues::decode(&binary).expect("decode");
                dump_edge_values(&data)
            }
            "arrays_test" => {
                let data = ArraysTest::decode(&binary).expect("decode");
                dump_arrays_test(&data)
            }
            "outer" => {
                let data = Outer::decode(&binary).expect("decode");
                dump_outer(&data)
            }
            "sparse_fields" => {
                let data = SparseFields::decode(&binary).expect("decode");
                dump_sparse_fields(&data)
            }
            other => {
                failures.push(format!("UNKNOWN STRUCT [{}:{}] {}", v.struct_name, v.case_name, other));
                continue;
            }
        };

        if decoded_dump != v.dump {
            failures.push(format!(
                "DECODE MISMATCH [{}:{}]\n  golden: {}\n  rust:   {}",
                v.struct_name, v.case_name, v.dump, decoded_dump
            ));
        }
    }

    if !failures.is_empty() {
        panic!("{} decode mismatch(es):\n{}", failures.len(), failures.join("\n"));
    }
}
