//! Golden vector tests for pack/unpack interop.
//!
//! Reads `tests/vectors_pack.txt` (generated by `tests/run.sh` from the C
//! reference) and verifies the Rust pack/unpack produces byte-identical results.
//!
//! The vectors file is NOT in the repo — it is regenerated on demand.
//! Run the orchestrator first: `tests/run.sh` (or `make -C tests/c` then
//! this test manually).
//!
//! Interop invariant: if every language implementation can
//!   1. pack(input) == golden packed bytes, and
//!   2. unpack(golden packed bytes) == input padded to 8,
//! then any two languages are automatically interoperable.

use std::path::PathBuf;
use zproto::Error;

fn vectors_path() -> PathBuf {
    // Allow override via env var for orchestrator flexibility.
    if let Ok(p) = std::env::var("ZPROTO_VECTORS") {
        return PathBuf::from(p);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("vectors_pack.txt")
}

struct Vector {
    name: String,
    input: Vec<u8>,
    packed: Vec<u8>,
}

fn parse_vectors(text: &str) -> Vec<Vector> {
    let mut vectors = Vec::new();
    let mut current_name = String::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('#') {
            let comment = &line[1..];
            if comment.trim() == "END" {
                break;
            }
            current_name = comment.trim().to_string();
            continue;
        }
        let parts: Vec<&str> = line.split_whitespace().collect();
        assert_eq!(parts.len(), 2, "malformed vector line: {}", line);
        let input = hex_decode(parts[0]);
        let packed = hex_decode(parts[1]);
        vectors.push(Vector {
            name: current_name.clone(),
            input,
            packed,
        });
    }
    vectors
}

fn hex_decode(hex: &str) -> Vec<u8> {
    assert!(hex.len() % 2 == 0, "odd-length hex string: {}", hex);
    (0..hex.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&hex[i..i + 2], 16)
                .unwrap_or_else(|e| panic!("bad hex at offset {}: {}", i, e))
        })
        .collect()
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

fn load_vectors() -> Vec<Vector> {
    let path = vectors_path();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {}. Run `tests/run.sh` (or `make -C tests/c`) first to generate vectors.",
            path.display(),
            e
        )
    });
    let vectors = parse_vectors(&text);
    assert!(!vectors.is_empty(), "no vectors in {}", path.display());
    vectors
}

#[test]
fn rust_pack_matches_golden_vectors() {
    let vectors = load_vectors();
    let mut failures = Vec::new();
    for v in &vectors {
        let rust_packed = zproto::pack(&v.input);
        if rust_packed != v.packed {
            failures.push(format!(
                "PACK MISMATCH [{}]: input {} bytes\n  golden: {}\n  rust:   {}",
                v.name,
                v.input.len(),
                hex_encode(&v.packed),
                hex_encode(&rust_packed),
            ));
        }
    }
    if !failures.is_empty() {
        panic!("{} pack mismatch(es):\n{}", failures.len(), failures.join("\n"));
    }
}

#[test]
fn rust_unpack_matches_golden_vectors() {
    let vectors = load_vectors();
    let mut failures = Vec::new();
    for v in &vectors {
        let rust_unpacked = match zproto::unpack(&v.packed) {
            Ok(data) => data,
            Err(e) => {
                failures.push(format!(
                    "UNPACK ERROR [{}]: {:?} packed={} bytes",
                    v.name, e, v.packed.len(),
                ));
                continue;
            }
        };
        let expected_len = ((v.input.len() + 7) / 8) * 8;
        if rust_unpacked.len() != expected_len {
            failures.push(format!(
                "UNPACK LEN [{}]: got {} expected {}",
                v.name, rust_unpacked.len(), expected_len,
            ));
            continue;
        }
        if &rust_unpacked[..v.input.len()] != &v.input[..] {
            failures.push(format!("UNPACK DATA [{}]: input mismatch", v.name));
            continue;
        }
        for (i, byte) in rust_unpacked[v.input.len()..].iter().enumerate() {
            if *byte != 0 {
                failures.push(format!(
                    "UNPACK PAD [{}] at offset {}: expected 0 got {}",
                    v.name, v.input.len() + i, byte,
                ));
                break;
            }
        }
    }
    if !failures.is_empty() {
        panic!("{} unpack mismatch(es):\n{}", failures.len(), failures.join("\n"));
    }
}

#[test]
fn rust_roundtrip_all_golden_vectors() {
    let vectors = load_vectors();
    for v in &vectors {
        let packed = zproto::pack(&v.input);
        let unpacked = zproto::unpack(&packed)
            .unwrap_or_else(|e| panic!("roundtrip unpack failed [{}]: {:?}", v.name, e));
        let expected_len = ((v.input.len() + 7) / 8) * 8;
        assert_eq!(unpacked.len(), expected_len, "roundtrip len [{}]", v.name);
        assert_eq!(&unpacked[..v.input.len()], &v.input[..], "roundtrip data [{}]", v.name);
    }
}

/// Malformed/truncated unpack inputs are rejected instead of silently padding
/// missing bytes with zeros. Rust surfaces this as Error::Malformed.
#[test]
fn rust_unpack_rejects_malformed_input() {
    // (name, packed_input)
    let cases: &[(&str, &[u8])] = &[
        // header=0xff (all 8 bits set, needs 8 data bytes) but 0 data bytes
        ("truncated-ff-only",   &[0xff]),
        // header=0x01 (bit 0 set, needs 1 data byte) but 0 data bytes
        ("truncated-01-only",   &[0x01]),
        // header=0xff, 1 data byte available (need 8)
        ("truncated-ff-1byte",  &[0xff, 0x42]),
        // header=0x55 (bits 0,2,4,6 set, needs 4 data bytes), 1 available
        ("truncated-55-1byte",  &[0x55, 0xaa]),
        // header=0x80 (bit 7 set, needs 1 data byte) but 0 data bytes
        ("truncated-80-0byte",  &[0x80]),
    ];

    let mut failures = Vec::new();
    for (name, packed) in cases {
        match zproto::unpack(packed) {
            Ok(unpacked) => {
                failures.push(format!(
                    "EXPECTED ERROR [{}] but got {} bytes: {}",
                    name, unpacked.len(), hex_encode(&unpacked),
                ));
            }
            Err(Error::Malformed) => { /* expected */ }
            Err(e) => {
                failures.push(format!(
                    "WRONG ERROR [{}]: got {:?} expected Malformed",
                    name, e,
                ));
            }
        }
    }
    if !failures.is_empty() {
        panic!("{} malformed unpack mismatch(es):\n{}", failures.len(), failures.join("\n"));
    }
}
